apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::654654620412:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-jMOFUNsDov5G
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::654654620412:user/harish
      username: harish
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-17T15:47:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1455"
  uid: be443309-9413-4077-9bdf-c274406ac69f #don't delete this